
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: rootroot
        driverClassName: com.mysql.jdbc.Driver
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
    thymeleaf:
      cache: false #禁用模板缓存
    profiles:
      active: prod #激活生产环境
server:
  port: 8081
debug: false


---
server:
  port: 8082
spring:
  profiles: prod
  messages:
    basename: i18n.login
logging:
  path: /Users/haominglfs/work-log

