
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: rootroot
        driverClassName: com.mysql.jdbc.Driver
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
    thymeleaf:
      cache: false
    profiles:
      active: prod
server:
  port: 8081


---
server:
  port: 8083
spring:
  profiles: prod